# Site settings

title: Nikolas Bompetsis
favicon: "/assest/images/favicon.png"
lang: en
email: nikolas_mpompetsis@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Nikolas Bompetsis Personal site

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Contact: 'contact'

baseurl: ""
url: "https://nbompetsis.github.io"
force-https: True

twitter_username: nick_bompetsis
facebook_username: Nikolas Allazw Tautotita
github_username: nbompetsis
linkedin_username: nbompetsis

footer_description: Nikolas' Personal site, created by <a href="http://jekyllrb.com" target="_blank">Jekyll</a>

# Build settings
markdown: kramdown

# Social
social_title: "github"
social_url: "https://github.com/nbompetsis"
  # - title: "linkedin"
  #   url: "https://www.linkedin.com/in/nikolas-bompetsis-b883b869/"
  # - title: "twitter"
  #   url: "https://twitter.com/nikosbob21"
