# Site settings

title: Nikolas Bompetsis
lang: en
favicon: "/assest/images/favicon.png"
baseurl: ""
url: "https://nbompetsis.github.io"
force-https: True

twitter_username: nikosbob21
github_username: nbompetsis
linkedin_username: nbompetsis
email: nikolas_mpompetsis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nikolas Bompetsis Personal site
footer_description: Check <a href="http://jekyllrb.com" target="_blank">Jekyll</a> awesome Web framework.
moto: Supporting OpenSource & Free World.

# Build settings
markdown: kramdown
