# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Life looks like LRU
email: nikolas_mmpompetsis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome personal site! It will be hosted by GitHub
baseurl: "nbompetsis.github.io" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nick_bompetsis
facebook_username: Nikolas Allazw Tautotita
github_username: nbompetsis

# Build settings
markdown: kramdown
